# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e76b7975b228990d4d9181a1844062fc3975d2ce2fc5f8d31179fc7cac75b54ea1656874788d21b22ac19758c00daf6158fa784a0d7d673b88c86ca00fb3f3

test:
  secret_key_base: 56d4fd8e6827f0362396a5a202e6921a9bbca915ba8cb64a006948d54d4d2413db0f6d405c997cd7890498302ce02e0eac4dd3ef480b87a5670a6aaf4eeb2e40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
